import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { notFound } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

const locales = ['en', 'pt']

interface RootLayoutProps {
  children: React.ReactNode
  params: {
    locale: string
  }
}

export const metadata: Metadata = {
  title: 'Sea of Thieves',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  if (!locales.includes(locale)) notFound()

  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
